# Generated by Django 4.1.3 on 2023-07-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembersData',
            fields=[
                ('rec_name', models.CharField(editable=False, max_length=100, verbose_name='Unique Name')),
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_list_as', models.CharField(max_length=100, verbose_name='Name List As')),
                ('name_display_as', models.CharField(max_length=100, verbose_name='Name Display As')),
                ('name_full_title', models.CharField(max_length=100, verbose_name='Name Full Title')),
                ('name_address_as', models.CharField(max_length=100, verbose_name='Name Address As')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, verbose_name='Gender')),
                ('thumbnail_url', models.URLField(verbose_name='Thumbnail URL')),
                ('latest_party_id', models.IntegerField(verbose_name='Latest Party ID')),
                ('latest_party_name', models.CharField(max_length=100, verbose_name='Latest Party Name')),
                ('latest_party_abbreviation', models.CharField(max_length=10, verbose_name='Latest Party Abbreviation')),
                ('latest_party_background_colour', models.CharField(max_length=7, verbose_name='Latest Party Background Colour')),
                ('latest_party_foreground_colour', models.CharField(max_length=7, verbose_name='Latest Party Foreground Colour')),
                ('latest_party_is_lords_main_party', models.BooleanField(verbose_name='Is Lords Main Party')),
                ('latest_party_is_lords_spiritual_party', models.BooleanField(verbose_name='Is Lords Spiritual Party')),
                ('latest_party_government_type', models.CharField(max_length=100, verbose_name='Latest Party Government Type')),
                ('latest_party_is_independent_party', models.BooleanField(verbose_name='Is Independent Party')),
                ('latest_house_membership_from', models.CharField(max_length=100, verbose_name='Latest House Membership From')),
                ('latest_house_membership_from_id', models.IntegerField(verbose_name='Latest House Membership From ID')),
                ('latest_house_membership_house', models.IntegerField(verbose_name='Latest House Membership House')),
                ('latest_house_membership_start_date', models.DateTimeField(verbose_name='Latest House Membership Start Date')),
                ('latest_house_membership_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Latest House Membership End Date')),
                ('latest_house_membership_end_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latest House Membership End Reason')),
                ('latest_house_membership_end_reason_notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latest House Membership End Reason Notes')),
                ('latest_house_membership_end_reason_id', models.IntegerField(blank=True, null=True, verbose_name='Latest House Membership End Reason ID')),
                ('membership_status_is_active', models.BooleanField(verbose_name='Membership Status Is Active')),
                ('membership_status_description', models.CharField(max_length=100, verbose_name='Membership Status Description')),
                ('membership_status_notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Membership Status Notes')),
                ('membership_status_id', models.IntegerField(verbose_name='Membership Status ID')),
                ('membership_status', models.IntegerField(verbose_name='Membership Status')),
                ('membership_status_start_date', models.DateTimeField(verbose_name='Membership Status Start Date')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
    ]
