# Generated by Django 4.1.3 on 2023-07-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rami', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersdata',
            name='membership_status',
        ),
    ]
