# Generated by Django 4.1.3 on 2023-07-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rami', '0003_alter_membersdata_latest_house_membership_end_reason_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersdata',
            name='latest_house_membership_end_reason_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Latest House Membership End Reason ID'),
        ),
    ]
