# Generated by Django 4.1.3 on 2023-07-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rami', '0004_alter_membersdata_latest_house_membership_end_reason_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersdata',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], editable=False, max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='latest_house_membership_from',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latest House Membership From'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='latest_house_membership_from_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Latest House Membership From ID'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='latest_house_membership_house',
            field=models.IntegerField(blank=True, null=True, verbose_name='Latest House Membership House'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='latest_house_membership_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Latest House Membership Start Date'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='latest_party_abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Latest Party Abbreviation'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='latest_party_background_colour',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Latest Party Background Colour'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='latest_party_foreground_colour',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Latest Party Foreground Colour'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='latest_party_government_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latest Party Government Type'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='latest_party_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Latest Party ID'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='latest_party_is_independent_party',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Independent Party'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='latest_party_is_lords_main_party',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Lords Main Party'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='latest_party_is_lords_spiritual_party',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Lords Spiritual Party'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='latest_party_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latest Party Name'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='member_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='membership_status_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Membership Status Description'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='membership_status_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Membership Status ID'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='membership_status_is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Membership Status Is Active'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='membership_status_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Membership Status Start Date'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='name_address_as',
            field=models.CharField(editable=False, max_length=100, verbose_name='Name Address As'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='name_display_as',
            field=models.CharField(editable=False, max_length=100, verbose_name='Name Display As'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='name_full_title',
            field=models.CharField(editable=False, max_length=100, verbose_name='Name Full Title'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='name_list_as',
            field=models.CharField(editable=False, max_length=100, verbose_name='Name List As'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='thumbnail_url',
            field=models.URLField(editable=False, verbose_name='Thumbnail URL'),
        ),
    ]
