# Generated by Django 4.1.3 on 2023-07-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rami', '0005_alter_membersdata_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersdata',
            name='membership_status_notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Membership Status Notes'),
        ),
    ]
