# Generated by Django 4.1.3 on 2023-07-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rami', '0006_alter_membersdata_membership_status_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersdata',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='member_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='name_address_as',
            field=models.CharField(max_length=100, verbose_name='Name Address As'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='name_display_as',
            field=models.CharField(max_length=100, verbose_name='Name Display As'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='name_full_title',
            field=models.CharField(max_length=100, verbose_name='Name Full Title'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='name_list_as',
            field=models.CharField(max_length=100, verbose_name='Name List As'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='rec_name',
            field=models.CharField(max_length=100, verbose_name='Unique Name'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='thumbnail_url',
            field=models.URLField(verbose_name='Thumbnail URL'),
        ),
    ]
