# Generated by Django 4.1.3 on 2023-07-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rami', '0007_alter_membersdata_gender_alter_membersdata_member_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersdata',
            name='latest_party_abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latest Party Abbreviation'),
        ),
    ]
