# Generated by Django 4.1.3 on 2023-07-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rami', '0008_alter_membersdata_latest_party_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersdata',
            name='contact_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membersdata',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membersdata',
            name='isPreferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membersdata',
            name='isWebAddress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membersdata',
            name='line1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membersdata',
            name='line2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membersdata',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membersdata',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='membersdata',
            name='postcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='membersdata',
            name='typeDescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membersdata',
            name='typeId',
            field=models.IntegerField(null=True),
        ),
    ]
