# Generated by Django 4.1.3 on 2023-07-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rami', '0012_alter_membersdata_latest_house_membership_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersdata',
            name='membership_status_notes',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Membership Status Notes'),
        ),
    ]
